package com.w2m.spaceShips.domain.enums;

/**
 * @author javiloguai
 */
public enum Equipment {

    SUPRALUMINUM_HYPERSPEED,
    QUANTUM_LEAP,
    WORMHOLE_DETECTOR,
    INVULNERABILITY_SHIELD,
    ARTIFICIAL_GRAVITY_GENERATOR,
    CARGO_HOLD,
    ANTIMATTER_ENGINE,
    WARP_ENGINE,
    INVISIBILITY,
    CRYOGENIC_CAPSULES,
    ARTIFICIAL_INTELLIGENCE_MATRIX,
    LASER_BLASTER,
    DEATH_RAY,
    EMP_ELECTROMAGNETIC_PULSE_GENERATOR,
    TERRAFORMING_EQUPMENT

}
